timezone_name: UTC
logs_dir: logs
web_root: web
jobs:
  - repository_name: "*"
    actions:
      - branch_name: "*"
        scripts:
          - bin/auto_deploy.sh
      - branch_name: master
        scripts:
          - bin/auto_deploy.sh
      - branch_name: develop
        scripts:
          - bin/auto_deploy.sh
  - repository_name: aklump/jquery.slim_time
    actions:
      - branch_name: master
        scripts:
        - /absolute/paths/are/fine/too
